CREATE TABLE DZIENNIK_UCZNIOW_LZ(
ID NUMBER PRIMARY KEY,
IMIE VARCHAR(50) NOT NULL,
NAZWISKO VARCHAR(50) NOT NULL,
OCENA_POL NUMBER,
OCENA_MAT NUMBER,
OCENA_ANG NUMBER,
OCENA_INF NUMBER,
OCENA_FIZ NUMBER,
SRED_ART NUMBER,
SRED_GEO NUMBER,
SRED_HAR NUMBER
);

SELECT * FROM DZIENNIK_UCZNIOW_LZ;

DROP TABLE DZIENNIK_UCZNIOW_ZL;

DROP TABLE DZIENNIK_UCZNIOW_LZ;

CREATE OR REPLACE PACKAGE DZIENNIK_LZ IS
  PROCEDURE WYPELNIJ_DZIENNIK_UCZNIOW_LZ;
  PROCEDURE WYCZYSCIC_DZIENNIK_UCZNIOW_LZ;

  TYPE P_DANE_UCZNIA IS RECORD (
    ID NUMBER,
    IMIE VARCHAR2(50),
    NAZWISKO VARCHAR2(50),
    OCENA_POL NUMBER,
    OCENA_MAT NUMBER,
    OCENA_ANG NUMBER,
    OCENA_INF NUMBER,
    OCENA_FIZ NUMBER,
    SRED_ART NUMBER,
    SRED_GEO NUMBER,
    SRED_HAR NUMBER
  );

  TYPE P_DANE_UCZNIOW IS TABLE OF P_DANE_UCZNIA;

  FUNCTION DAJ_DANE_UCZNIOW_LZ(
    P_RODZAJ_SREDNIEJ IN VARCHAR2,
    P_SREDNIA_OD IN NUMBER DEFAULT NULL,
    P_SREDNIA_DO IN NUMBER DEFAULT NULL
  ) RETURN P_DANE_UCZNIOW PIPELINED;
END;
/

CREATE OR REPLACE PACKAGE BODY DZIENNIK_LZ IS
  PROCEDURE WYPELNIJ_DZIENNIK_UCZNIOW_LZ IS
    V_ID NUMBER;
    V_IMIE VARCHAR2(50);
    V_NAZWISKO VARCHAR2(50);

    V_ALFABET VARCHAR2(23) := 'ABCDEFGHIJKLMNOPRSTUWYZ';

    V_DL_IMIE NUMBER;
    V_DL_NAZWISKO NUMBER;
    V_INDEKS NUMBER;

    V_OCENA_POL NUMBER;
    V_OCENA_MAT NUMBER;
    V_OCENA_ANG NUMBER;
    V_OCENA_INF NUMBER;
    V_OCENA_FIZ NUMBER;

    V_SREDNIA_ART NUMBER;
    V_SREDNIA_GEO NUMBER;
    V_SREDNIA_HAR NUMBER;

  BEGIN
    FOR i IN 1..100 LOOP
      V_ID := i;
      V_DL_IMIE := ROUND(DBMS_RANDOM.VALUE(4,8));
      V_DL_NAZWISKO := ROUND(DBMS_RANDOM.VALUE(4,8));
      V_IMIE := '';
      V_NAZWISKO := '';

      FOR j IN 1..V_DL_IMIE LOOP
        V_INDEKS := ROUND(DBMS_RANDOM.VALUE(1, LENGTH(V_ALFABET)));
        V_IMIE := V_IMIE || SUBSTR(V_ALFABET, V_INDEKS, 1);
      END LOOP;

      FOR j IN 1..V_DL_NAZWISKO LOOP
        V_INDEKS := ROUND(DBMS_RANDOM.VALUE(1, LENGTH(V_ALFABET)));
        V_NAZWISKO := V_NAZWISKO || SUBSTR(V_ALFABET, V_INDEKS, 1);
      END LOOP;

      V_OCENA_POL := ROUND(DBMS_RANDOM.VALUE(1,6));
      V_OCENA_MAT := ROUND(DBMS_RANDOM.VALUE(1,6));
      V_OCENA_ANG := ROUND(DBMS_RANDOM.VALUE(1,6));
      V_OCENA_INF := ROUND(DBMS_RANDOM.VALUE(1,6));
      V_OCENA_FIZ := ROUND(DBMS_RANDOM.VALUE(1,6));

      V_SREDNIA_ART := (V_OCENA_POL + V_OCENA_MAT + V_OCENA_ANG + V_OCENA_INF + V_OCENA_FIZ) / 5;
      V_SREDNIA_GEO := ROUND(POWER(SQRT(V_OCENA_POL * V_OCENA_MAT * V_OCENA_ANG * V_OCENA_INF * V_OCENA_FIZ), 0.2), 2);
      V_SREDNIA_HAR := ROUND(5 / (1 / V_OCENA_POL + 1 / V_OCENA_MAT + 1 / V_OCENA_ANG + 1 / V_OCENA_INF + 1 / V_OCENA_FIZ), 2);

      INSERT INTO DZIENNIK_UCZNIOW_LZ (ID, IMIE, NAZWISKO, OCENA_POL, OCENA_MAT, OCENA_ANG, OCENA_INF, OCENA_FIZ, SRED_ART, SRED_GEO, SRED_HAR)
      VALUES (V_ID, V_IMIE, V_NAZWISKO, V_OCENA_POL, V_OCENA_MAT, V_OCENA_ANG, V_OCENA_INF, V_OCENA_FIZ, V_SREDNIA_ART, V_SREDNIA_GEO, V_SREDNIA_HAR);
    END LOOP;

  END WYPELNIJ_DZIENNIK_UCZNIOW_LZ;

  PROCEDURE WYCZYSCIC_DZIENNIK_UCZNIOW_LZ IS
  BEGIN
    DELETE FROM DZIENNIK_UCZNIOW_LZ;
  END WYCZYSCIC_DZIENNIK_UCZNIOW_LZ;

  FUNCTION DAJ_DANE_UCZNIOW_LZ(
    P_RODZAJ_SREDNIEJ IN VARCHAR2,
    P_SREDNIA_OD IN NUMBER DEFAULT NULL,
    P_SREDNIA_DO IN NUMBER DEFAULT NULL
  ) RETURN P_DANE_UCZNIOW PIPELINED
  IS
    V_DANE_UCZNIA P_DANE_UCZNIA;
  BEGIN
    FOR C IN (SELECT * FROM DZIENNIK_UCZNIOW_LZ) LOOP
      IF P_RODZAJ_SREDNIEJ = 'ARYTMETYCZNA' THEN
        IF P_SREDNIA_OD IS NOT NULL AND P_SREDNIA_DO IS NOT NULL THEN
          IF C.SRED_ART BETWEEN P_SREDNIA_OD AND P_SREDNIA_DO THEN
            V_DANE_UCZNIA := C;
            PIPE ROW(V_DANE_UCZNIA);
          END IF;
        ELSE
          V_DANE_UCZNIA := C;
          PIPE ROW(V_DANE_UCZNIA);
        END IF;
      ELSIF P_RODZAJ_SREDNIEJ = 'GEOMETRYCZNA' THEN
        IF P_SREDNIA_OD IS NOT NULL AND P_SREDNIA_DO IS NOT NULL THEN
          IF C.SRED_GEO BETWEEN P_SREDNIA_OD AND P_SREDNIA_DO THEN
            V_DANE_UCZNIA := C;
            PIPE ROW(V_DANE_UCZNIA);
          END IF;
        ELSE
          V_DANE_UCZNIA := C;
          PIPE ROW(V_DANE_UCZNIA);
        END IF;
      ELSIF P_RODZAJ_SREDNIEJ = 'HARMONICZNA' THEN
        IF P_SREDNIA_OD IS NOT NULL AND P_SREDNIA_DO IS NOT NULL THEN
          IF C.SRED_HAR BETWEEN P_SREDNIA_OD AND P_SREDNIA_DO THEN
            V_DANE_UCZNIA := C;
            PIPE ROW(V_DANE_UCZNIA);
          END IF;
        ELSE
          V_DANE_UCZNIA := C;
          PIPE ROW(V_DANE_UCZNIA);
        END IF;
       END IF;
    END LOOP;

    RETURN;
END DAJ_DANE_UCZNIOW_LZ;
END;
/
BEGIN
DZIENNIK_LZ.WYPELNIJ_DZIENNIK_UCZNIOW_LZ;
END;
/
BEGIN
DZIENNIK_LZ.WYCZYSCIC_DZIENNIK_UCZNIOW_LZ;
END;
/

SELECT * FROM TABLE (DZIENNIK_LZ.DAJ_DANE_UCZNIOW_LZ('HARMONICZNA', 3.5, 4.6 ));

/
SELECT * FROM DZIENNIK_UCZNIOW_LZ;